<?php

namespace SingPlus\Domains\Works\Models;

use SingPlus\Support\Database\Eloquent\MongodbModel;

class Work extends MongodbModel
{
  const STATUS_DELETED = 0;
  const STATUS_NORMAL = 1;
  const STATUS_CHORUS_ACCOMPANIMENT_PREPARE = 2;     // 合唱伴奏准备中

  const NO_ACCOMPANIMENT_NO = 0;
  const NO_ACCOMPANIMENT_YES = 1;

  const IS_PRIVATE_NO = 0;
  const IS_PRIVATE_YES = 1;

  // constant for is_default_cover
  const DEFAULT_COVER_NO = 0;
  const DEFAULT_COVER_YES = 1;

  protected $collection = 'works';

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'user_id',
    'music_id',
    'name',
    'resource',
    'duration',
    'cover',            // cover image uri
    'is_default_cover', // please to see self::DEFAULT_COVER_XXXX
    'slides',           // elements are user image uri
    'description',      // description for work, used for share default text
    'listens',
    'listen_count',     // listen count
    'favourite_count',  // favourites count
    'comment_count',
    'transmits',
    'transmit_count',   // transmits count from sing+
    'display_order',
    'client_id',        // generated by client, prevent client from uploading more than once
    'no_accompaniment',
    'is_private',
    'chorus_type',      // @see \SingPlus\Contracts\Works\Constants\WorkConstant::CHORUS_TYPE_XXXX         
    'chorus_start_info',    // exists when chorus_type == CHORUS_TYPE_START
                            // array, elements are
                            //      - chorus_count int
                            //      - resource array    work accompaniment resource
                            //        - zip string      accompaniment resource zip uri
    'chorus_join_info',     // exists when chorus_type == CHORUS_TYPE_JOIN
                            // array, elements are
                            //      - origin_work_id string   work id, which be joined
    'regional_recommend_status',    // dict (记录对地区推荐状态，admin维护并使用)
    'country_abbr',         // country code, upper case
    'status',
    'gift_info',            //dict  作品收到的礼物统计{ "gift_amount" : 1000,"gift_coin_amount" : 1000,"gift_popularity_amount" : 10222 }
    'popularity',           // int 作品的人气
    'work_tags',            // array, elements are string , the title of work_tag

  ];

  public function isNormal() : bool
  {
    return in_array($this->status, [
                        self::STATUS_NORMAL,
                        self::STATUS_CHORUS_ACCOMPANIMENT_PREPARE,
                      ]);
  }

  public function isChorusAccompanimentPrepare() : bool
  {
    return $this->status == self::STATUS_CHORUS_ACCOMPANIMENT_PREPARE;
  }

  public function noAccompaniment() : bool
  {
    return (isset($this->no_accompaniment) && $this->no_accompaniment == self::NO_ACCOMPANIMENT_YES) ? true : false;
  }

  public function isDefaultCover() : bool
  {
    return (isset($this->is_default_cover) && $this->is_default_cover == self::DEFAULT_COVER_YES) ? true : false;
  }

  public function isPrivate() : bool
  {
    return (isset($this->is_private) && $this->is_private == self::IS_PRIVATE_YES) ? true : false;
  }

  //==================================
  //      Relation
  //==================================
}
